// SolidJS/src/Settings.jsx
import ear from "rabbit-ear";
import { createSignal } from "solid-js";
import styles from "./Settings.module.css";
import FileInfo from "./FileInfo";
import Examples from "./Examples";

function Settings(props) {

  const fileDialogDidLoad = (string, filename, mimeType) => {
    try { props.loadFOLD(JSON.parse(string)); }
    catch (error) { window.alert(error); }
  };

  const fileDialogOnInput = (e) => {
    const file = e.target.files[0];
    let mimeType, filename;
    const reader = new FileReader();
    reader.onload = loadEvent => fileDialogDidLoad(loadEvent.target.result, filename, mimeType);
    if (e.target.files.length) {
      mimeType = e.target.files[0].type;
      filename = e.target.files[0].name;
      reader.readAsText(e.target.files[0]);
    }
  }

  return (
    <div class={styles.Settings}>

      <h3>load FOLD</h3>
      <input type="file" onInput={fileDialogOnInput} />

      <hr />

      <Examples
        loadFOLD={props.loadFOLD}
        selectedExample={props.selectedExample}
        setSelectedExample={props.setSelectedExample}
      />

      <hr />

      <h3>file info</h3>

      <Show when={props.frames().length > 1}>
        <p>
          frame: <span class="value">{props.selectedFrame()+1}/{props.frames().length}</span>
        </p>
        <div>
          <input
            type="range"
            min="0"
            max={props.frames().length - 1}
            step="1"
            value={props.selectedFrame()}
            onInput={e => props.setSelectedFrame(e.target.value)} />
        </div>
      </Show>

      <FileInfo
        FOLD={props.FOLD}
        frames={props.frames}
        selectedFrame={props.selectedFrame}
      />

      <hr />

      <h3>viewport</h3>
      <input
        type="radio"
        name="radio-webgl-perspective"
        value="radio-webgl-perspective-orthographic"
        onClick={() => props.setPerspective("orthographic")}
        checked={props.perspective() === "orthographic"} />
      <label for="radio-webgl-perspective-orthographic">orthographic</label>
      <input
        type="radio"
        name="radio-webgl-perspective"
        value="radio-webgl-perspective-perspective"
        onClick={() => props.setPerspective("perspective")}
        checked={props.perspective() === "perspective"} />
      <label for="radio-webgl-perspective-perspective">perspective</label>

      <br />

      <Show when={props.perspective() === "perspective"}>
        <span>field of view:</span>
        <input
          class={styles.ShortInput}
          type="text"
          placeholder="field of view"
          value={props.fov()}
          onInput={(e) => props.setFov(e.target.value)}
        />
        <br/>
      </Show>

      <span>flip over</span>
      <input
        type="checkbox"
        checked={props.flipCameraZ()}
        onClick={() => props.setFlipCameraZ(!props.flipCameraZ())}
      />

      <hr />

      <h3>style</h3>
      <input
        type="radio"
        name="radio-view-class"
        value="radio-view-class-crease-pattern"
        onClick={() => props.setViewClass("creasePattern")}
        checked={props.viewClass()==="creasePattern"} />
      <label for="radio-view-class-crease-pattern">crease pattern</label>
      <input
        type="radio"
        name="radio-view-class"
        value="radio-view-class-folded-form"
        onClick={() => props.setViewClass("foldedForm")}
        checked={props.viewClass()==="foldedForm"} />
      <label for="radio-view-class-folded-form">folded form</label>
      <br />
      <Show when={props.viewClass() === "creasePattern"}>
        <span>stroke width</span>
        <input
          type="range"
          min="0.001"
          max="0.2"
          step="0.001"
          value={props.strokeWidth()}
          onInput={e => props.setStrokeWidth(e.target.value)} />
      </Show>
      <Show when={props.viewClass() === "foldedForm"}>
        <span>opacity</span>
        <input
          type="range"
          min="0"
          max="1"
          step="0.01"
          value={props.opacity()}
          onInput={e => props.setOpacity(e.target.value)} />
        <br />
        <span>front</span><input
          type="text"
          class={styles.ShortInput}
          value={props.frontColor()}
          onInput={(e) => props.setFrontColor(e.target.value)}
        />
        <span>back</span><input
          type="text"
          class={styles.ShortInput}
          value={props.backColor()}
          onInput={(e) => props.setBackColor(e.target.value)}
        />
      </Show>

      <Show when={props.viewClass() === "foldedForm"}>
        <br/>
        <span>show faces</span>
        <input
          type="checkbox"
          checked={props.showFoldedFaces()}
          onClick={() => props.setShowFoldedFaces(!props.showFoldedFaces())}
        />
        <br/>
        <span>face outlines</span>
        <input
          type="checkbox"
          checked={props.showFoldedFaceOutlines()}
          onClick={() => props.setShowFoldedFaceOutlines(!props.showFoldedFaceOutlines())}
          disabled={!props.showFoldedFaces()}
        />
        <br/>
        <span>show creases</span>
        <input
          type="checkbox"
          checked={props.showFoldedCreases()}
          onClick={() => props.setShowFoldedCreases(!props.showFoldedCreases())}
        />
        <br/>
        <span>stroke width</span><input
          type="range"
          min="1"
          max="20"
          step="0.01"
          value={props.strokeWidthSlider()}
          onInput={e => props.setStrokeWidthSlider(e.target.value)}
          disabled={!props.showFoldedCreases()}
        />
        <br/>
      </Show>
      <Show when={props.viewClass() === "foldedForm" && props.origami !== undefined}>
        <Show when={props.origami.faceOrders || props.origami.faces_layer}>
          <hr />
          <h3>overlapping faces</h3>
          <span>explode layers</span><input
            type="range"
            min="1"
            max="20"
            step="0.01"
            value={props.layerNudgeSlider()}
            onInput={e => props.setLayerNudgeSlider(e.target.value)}
          />
          <br />
          <input
            type="text"
            class={styles.LongInput}
            value={props.layerNudge()}
            onInput={(e) => props.setLayerNudge(e.target.value)}
          />
        </Show>
      </Show>

    </div>
  );
}

export default Settings;

// Svelte/src/Settings/Settings.svelte
<script>
	import Examples from "./Examples.svelte";
	import FileContents from "./FileContents.svelte";
	import StylePanel from "./StylePanel.svelte";

	export let origami = {};
	export let frames = [];
	export let selectedFrame = 0;
	export let perspective = "orthographic";
	export let viewClass = "creasePattern";
	export let layerNudge = 1e-5;
	export let opacity = 1.0;
	export let fov = 30;
	export let flipCameraZ = false;
	export let frontColor = "#57f";
	export let backColor = "#fff";
	export let showFoldedCreases = false;
	export let showFoldedFaces = true;
	export let showFoldedFaceOutlines = true;
	export let loadFOLD = () => {};

	export let strokeWidthSlider;
	export let layerNudgeSlider;

	let selectedExample;
	let showFileContents = true;
	let showStyle = false;

	const fileDialogDidLoad = (string, filename, mimeType) => {
		try {
			loadFOLD(JSON.parse(string));
			selectedExample = null;
		}
		catch (error) { window.alert(error); }
	};

	let files;
	$: if (files) {
		const file = files[0];
		let mimeType, filename;
		const reader = new FileReader();
		reader.onload = loadEvent => fileDialogDidLoad(loadEvent.target.result, filename, mimeType);
		if (files.length) {
			mimeType = files[0].type;
			filename = files[0].name;
			reader.readAsText(files[0]);
		}
	}

</script>

<div class="settings">
	<h3>load FOLD</h3>
	<input type="file" bind:files>

	<!-- <hr /> -->
	<br />

	<Examples {loadFOLD} bind:selectedExample={selectedExample} />

	<div
		class="dropdown"
		on:click={() => showFileContents = !showFileContents}>
		<h3>file contents</h3>
		{#if showFileContents}
			<span class="triangle">▼</span>
		{/if}
		{#if !showFileContents}
			<span class="triangle rotated">▼</span>
		{/if}
	</div>

	{#if showFileContents}
		<FileContents
			FOLD={origami}
			{frames}
			{selectedFrame}
		/>
	{/if}

	<div
		class="dropdown"
		on:click={() => showStyle = !showStyle}>
		<h3>style</h3>
		{#if showStyle}
			<span class="triangle">▼</span>
		{/if}
		{#if !showStyle}
			<span class="triangle rotated">▼</span>
		{/if}
	</div>

	{#if showStyle}
		<StylePanel
			{origami}
			{frames}
			{selectedFrame}
			{perspective}
			{viewClass}
			{layerNudge}
			{opacity}
			{fov}
			{flipCameraZ}
			{frontColor}
			{backColor}
			{showFoldedCreases}
			{showFoldedFaces}
			{showFoldedFaceOutlines}
			{strokeWidthSlider}
			{layerNudgeSlider}
		/>
	{/if}

</div>

<style>
	.settings {
		background-color: #0002;
		z-index: 2;
		position: absolute;
		top: 0;
		left: 0;
		padding: 0.5rem;
		overflow-y: auto;
		max-height: 100vh;
	}
	h3 {
		margin: 0;
		padding: 0;
	}
	.dropdown {
		text-transform: uppercase;
		letter-spacing: 0.15rem;
		background-color: #4444;
		margin: 0.25rem -0.5rem;
		padding: 0rem 0.5rem;
		border: 0 solid #666;
		border-top-width: 1px;
		border-bottom-width: 1px;
		display: flex;
		flex-direction: row;
		justify-content: space-between;
		cursor: pointer;
	}
	.dropdown:hover {
		background-color: #6664;
	}
	.dropdown h3 {
		font-size: 1rem;
	}
	input[type=text] {
		width: 4rem;
	}
	input[type=text].long-input {
		width: 8rem;
	}
	span + input[type=text] {
		margin-left: 0.5rem;
	}
	span.rotated {
		transform: rotate(90deg);
	}
</style>
