// Svelte/src/Settings/Examples.svelte
<script>
	import { onMount } from "svelte";

	import craneCP from "../../../fold/crane-cp.fold?raw";
	import birdCP from "../../../fold/kraft-bird-base.fold?raw";
	import craneFolded from "../../../fold/crane-folded.fold?raw";
	import moosersTrain from "../../../fold/moosers-train.fold?raw";
	import polygami from "../../../fold/polygami.fold?raw";
	import blintzFrames from "../../../fold/blintz-frames.fold?raw";
	import kabuto from "../../../fold/kabuto.fold?raw";

	export let loadFOLD = () => {};

	export let selectedExample = "placeholder";
	$: selectedExample == null || selectedExample === "placeholder"
		? (() => {})()
		: loadFOLD(JSON.parse(exampleData[selectedExample]));

	const exampleData = {
		craneCP, birdCP, craneFolded, moosersTrain,
		blintzFrames, kabuto, polygami,
	};
	const examples = [
		{ text: "crease pattern: crane", data: "craneCP" },
		{ text: "crease pattern: bird", data: "birdCP" },
		{ text: "folded: crane", data: "craneFolded" },
		{ text: "folded: Mooser's train", data: "moosersTrain" },
		{ text: "folded: polygami", data: "polygami" },
		{ text: "frames: kabuto", data: "kabuto" },
		{ text: "frames: blintz base", data: "blintzFrames" },
	];

	// load example on start
	// onMount(() => selectedExample = "craneFolded");
	onMount(() => selectedExample = "placeholder");

</script>

	<select bind:value={selectedExample}>
    <option value="placeholder" disabled selected>load example</option>
		{#each examples as example}
			<option value={example.data}>
				{example.text}
			</option>
		{/each}
	</select>

// SolidJS/src/Examples.jsx
import { onMount, createEffect } from "solid-js";

// example FOLD files
import craneCP from "../../fold/crane-cp.fold?raw";
import craneFolded from "../../fold/crane-folded.fold?raw";
import moosers3d from "../../fold/moosers-train.fold?raw";
import blintzFrames from "../../fold/blintz-frames.fold?raw";
import kabuto from "../../fold/kabuto.fold?raw";
import polygami from "../../fold/polygami.fold?raw";
import kraftBird from "../../fold/kraft-bird-base-06-mvf.fold?raw";

const exampleData = {
	craneCP, craneFolded, moosers3d,
	blintzFrames, kabuto, polygami, kraftBird,
};

const examples = [
	{ text: "crease pattern: crane", data: "craneCP" },
	{ text: "crease pattern: bird", data: "kraftBird" },
	{ text: "folded: crane", data: "craneFolded" },
	{ text: "folded: Mooser's train", data: "moosers3d" },
	{ text: "folded: polygami", data: "polygami" },
	{ text: "frames: kabuto", data: "kabuto" },
	{ text: "frames: blintz base", data: "blintzFrames" },
];

// load example on start
// onMount(() => selectedExample = "craneCP");

const Examples = (props) => {

	createEffect(() => props.selectedExample() == null
		? (() => {})()
		: props.loadFOLD(JSON.parse(exampleData[props.selectedExample()])))

	return (<>
		<h3>example:</h3>
    <select
    	value={props.selectedExample()}
    	onInput={e => props.setSelectedExample(e.currentTarget.value)}>
			<For each={examples}>{example =>
				<option value={example.data}>
					{example.text}
				</option>
			}</For>
	</select>
	</>);
};

export default Examples;
