// SolidJS/src/App.jsx
import styles from './App.module.css';
import { createSignal, onMount } from "solid-js";

import Settings from "./Settings";
import WebGLView from "./WebGLView";

import craneCP from "../../fold/crane-cp.fold?raw";

function App() {
  // the origami
  const [origami, setOrigami] = createSignal({});
  // view options
  const [perspective, setPerspective] = createSignal("orthographic");
  const [viewClass, setViewClass] = createSignal("creasePattern");
  const [strokeWidth, setStrokeWidth] = createSignal(0.0025);
  const [opacity, setOpacity] = createSignal(1.0);
  const [fov, setFov] = createSignal(45);

  const loadFOLD = (result) => {
    setOrigami(result);
    // update view style according to file type
    if (origami().frame_classes) {
      if (origami().frame_classes.includes("creasePattern")) {
        setPerspective("orthographic");
        setViewClass("creasePattern");
      } else if (origami().frame_classes.includes("foldedForm")) {
        setPerspective("perspective");
        setViewClass("foldedForm");
      }
    }
  };

  // load example on start
  onMount(() => loadFOLD(JSON.parse(craneCP)));

  return (
    <div class={styles.App}>
      <WebGLView
        origami={origami}
        viewClass={viewClass}
        perspective={perspective}
        strokeWidth={strokeWidth}
        opacity={opacity}
        fov={fov}
      />
      <Settings
        perspective={perspective}
        setPerspective={setPerspective}
        viewClass={viewClass}
        setViewClass={setViewClass}
        strokeWidth={strokeWidth}
        setStrokeWidth={setStrokeWidth}
        opacity={opacity}
        setOpacity={setOpacity}
        fov={fov}
        setFov={setFov}
        loadFOLD={loadFOLD}
        origami={origami}
      />
    </div>
  );
}

export default App;

// src/App.svelte
<script>
	import { onMount } from "svelte";
	import Settings from "./Settings.svelte";
	import WebGL from "./WebGL/WebGL.svelte";

	import craneCP from "./fold/crane-cp.fold?raw";

	// the origami
	let origami = {};
	// view options
	let perspective = "orthographic";
	let viewClass = "creasePattern"; //"foldedForm"; //"creasePattern";
	let strokeWidth = 0.0025;
	let opacity = 1.0;
	let fov = 45;

	const loadFOLD = (result) => {
		origami = result;
		// update view style according to file type
		if (origami.frame_classes) {
			if (origami.frame_classes.includes("creasePattern")) {
				perspective = "orthographic";
				viewClass = "creasePattern";
			} else if (origami.frame_classes.includes("foldedForm")) {
				perspective = "perspective";
				viewClass = "foldedForm";
			}
		}
	};

	// load example on start
	onMount(() => loadFOLD(JSON.parse(craneCP)));

</script>

<main>
	<WebGL {origami} {viewClass} {perspective} {strokeWidth} {opacity} {fov} />
	<Settings
		bind:perspective={perspective}
		bind:viewClass={viewClass}
		bind:strokeWidth={strokeWidth}
		bind:opacity={opacity}
		bind:fov={fov}
		{loadFOLD}
		{origami}
		/>
</main>

<style>
	main {
		height: 100%;
		overflow: hidden;
	}
</style>
